services:
  - type: web
    name: azobss-lucky-draw-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://azobss.com
      - key: TZ
        value: Asia/Kuala_Lumpur
